export const runtime = "nodejs";
export const dynamic = "force-dynamic";

import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import React from "react";
import {
  Document,
  Page,
  Text,
  StyleSheet,
  pdf,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
  },
  title: {
    fontSize: 18,
    textAlign: "center",
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 14,
    textAlign: "center",
    marginBottom: 6,
  },
  confidential: {
    fontSize: 12,
    textAlign: "center",
    color: "red",
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 13,
    marginBottom: 6,
    marginTop: 12,
  },
  text: {
    fontSize: 11,
    marginBottom: 6,
    lineHeight: 1.5,
  },
  legal: {
    fontSize: 9,
    marginTop: 20,
    lineHeight: 1.4,
  },
  footer: {
    fontSize: 9,
    textAlign: "right",
    marginTop: 20,
  },
});

export async function GET() {
  // Fetch only board-approved decisions
  const decisions = await prisma.decision.findMany({
    where: { includedInReport: true },
  });

  const total = decisions.length;
  const highRisk = decisions.filter(d => d.riskScore >= 70).length;
  const mediumRisk = decisions.filter(
    d => d.riskScore >= 40 && d.riskScore < 70
  ).length;

  const date = new Date().toLocaleDateString();

  const Report = React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: "A4", style: styles.page },

      // Header
      React.createElement(Text, { style: styles.title }, "AnkismaikT DecisionOS"),
      React.createElement(
        Text,
        { style: styles.subtitle },
        "Board Decision Intelligence Report"
      ),
      React.createElement(
        Text,
        { style: styles.confidential },
        "CONFIDENTIAL"
      ),

      // Executive Summary
      React.createElement(
        Text,
        { style: styles.sectionTitle },
        "Executive Summary"
      ),
      React.createElement(
        Text,
        { style: styles.text },
        `This report consolidates ${total} strategic decisions recorded within AnkismaikT DecisionOS. Primary decision activity is concentrated across mixed operational and strategic domains. The organization maintains a balanced and controlled risk posture.`
      ),

      // Risk Overview
      React.createElement(
        Text,
        { style: styles.sectionTitle },
        "Risk Overview"
      ),
      React.createElement(
        Text,
        { style: styles.text },
        `• High / Severe Risk Decisions: ${highRisk}`
      ),
      React.createElement(
        Text,
        { style: styles.text },
        `• Medium Risk Decisions: ${mediumRisk}`
      ),
      React.createElement(
        Text,
        { style: styles.text },
        `• Total Decisions Assessed: ${total}`
      ),

      // Board Recommendation
      React.createElement(
        Text,
        { style: styles.sectionTitle },
        "Board Recommendation"
      ),
      React.createElement(
        Text,
        { style: styles.text },
        "Current initiatives are aligned with acceptable risk tolerance. Continued execution is recommended, subject to periodic review and governance oversight."
      ),

      // Legal / Authorization
      React.createElement(
        Text,
        { style: styles.sectionTitle },
        "Authorization & Disclaimer"
      ),
      React.createElement(
        Text,
        { style: styles.legal },
        "This report has been generated by AnkismaikT DecisionOS™, an AI-powered decision intelligence system designed to support executive and board-level strategic evaluation. All insights, risk assessments, and recommendations contained herein are advisory in nature. Final accountability, fiduciary responsibility, and statutory compliance remain solely with the organization’s leadership and board of directors.\n\nPrepared by: AnkismaikT DecisionOS™\nAuthorized for Internal Board Use Only\n© 2026 AnkismaikT Technologies Pvt. Ltd. · Confidential"
      ),

      // Footer
      React.createElement(
        Text,
        { style: styles.footer },
        `Generated on ${date} | Page 1`
      )
    )
  );

  const buffer = await pdf(Report).toBuffer();

  return new NextResponse(buffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition":
        "attachment; filename=DecisionOS-Board-Report.pdf",
    },
  });
}

